#!/usr/bin/env bash
# ============================================================
# CareerSwarm — One-Shot Setup Script
# Runs from your local machine where you have browser access.
# Requires: gh, supabase, vercel, node CLIs installed.
# Install missing ones: brew install gh supabase/tap/supabase vercel
# ============================================================

set -e

GITHUB_USER="zganich"
REPO_NAME="careerswarm"
VERCEL_PROJECT_NAME="careerswarm"
SUPABASE_PROJECT_NAME="careerswarm"
SUPABASE_REGION="us-east-1"
SUPABASE_DB_PASSWORD=$(openssl rand -base64 24)

BOLD=$(tput bold 2>/dev/null || echo '')
GREEN=$(tput setaf 2 2>/dev/null || echo '')
AMBER=$(tput setaf 3 2>/dev/null || echo '')
RESET=$(tput sgr0 2>/dev/null || echo '')

step() { echo ""; echo "${AMBER}${BOLD}▶ $1${RESET}"; }
ok()   { echo "${GREEN}✓ $1${RESET}"; }

# ─── PREFLIGHT ────────────────────────────────────────────────
step "Checking CLI tools"
for cmd in gh supabase vercel node npm; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Missing: $cmd"
    echo "Install with: brew install gh supabase/tap/supabase vercel"
    exit 1
  fi
done
ok "All CLIs present"

# ─── GITHUB ───────────────────────────────────────────────────
step "1/3 — Setting up GitHub repo"

if ! gh auth status &>/dev/null; then
  echo "Opening GitHub login..."
  gh auth login
fi

if gh repo view "$GITHUB_USER/$REPO_NAME" &>/dev/null; then
  ok "Repo already exists: github.com/$GITHUB_USER/$REPO_NAME"
else
  gh repo create "$GITHUB_USER/$REPO_NAME" \
    --private \
    --description "AI Application Engine for Executives" \
    --clone=false
  ok "Created: github.com/$GITHUB_USER/$REPO_NAME"
fi

# Add GitHub as remote if not already set
if ! git remote get-url github &>/dev/null; then
  git remote add github "https://github.com/$GITHUB_USER/$REPO_NAME.git"
  ok "Added github remote"
fi

git push github HEAD:main --force
ok "Code pushed to github.com/$GITHUB_USER/$REPO_NAME"

# ─── SUPABASE ─────────────────────────────────────────────────
step "2/3 — Setting up Supabase"

if ! supabase projects list &>/dev/null; then
  echo "Opening Supabase login..."
  supabase login
fi

# Get org ID
ORG_ID=$(supabase orgs list --output json 2>/dev/null | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
if [ -z "$ORG_ID" ]; then
  echo "Could not find Supabase org ID. Run: supabase orgs list"
  exit 1
fi
ok "Supabase org: $ORG_ID"

# Create project
echo "Creating Supabase project '$SUPABASE_PROJECT_NAME'..."
PROJECT_JSON=$(supabase projects create "$SUPABASE_PROJECT_NAME" \
  --org-id "$ORG_ID" \
  --region "$SUPABASE_REGION" \
  --db-password "$SUPABASE_DB_PASSWORD" \
  --output json 2>/dev/null)

PROJECT_REF=$(echo "$PROJECT_JSON" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
if [ -z "$PROJECT_REF" ]; then
  echo "Project may already exist. Finding project ref..."
  PROJECT_REF=$(supabase projects list --output json 2>/dev/null | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)
fi
ok "Project ref: $PROJECT_REF"

echo "Waiting 30s for Supabase project to provision..."
sleep 30

# Link and push schema
supabase link --project-ref "$PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"
supabase db push
ok "Schema pushed to Supabase"

# Get API keys
SUPABASE_URL="https://$PROJECT_REF.supabase.co"
ANON_KEY=$(supabase projects api-keys --project-ref "$PROJECT_REF" --output json 2>/dev/null | grep -A1 '"anon"' | grep '"apikey"' | cut -d'"' -f4)
SERVICE_KEY=$(supabase projects api-keys --project-ref "$PROJECT_REF" --output json 2>/dev/null | grep -A1 '"service_role"' | grep '"apikey"' | cut -d'"' -f4)

ok "Supabase configured: $SUPABASE_URL"

# ─── ENV FILE ─────────────────────────────────────────────────
step "Writing .env.local"

cat > .env.local <<EOF
# Auto-generated by setup.sh on $(date)

ANTHROPIC_API_KEY=sk-ant-REPLACE_ME

NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

NEXT_PUBLIC_APP_URL=https://$VERCEL_PROJECT_NAME.vercel.app
EOF

echo ""
echo "${AMBER}ACTION REQUIRED: Add your Anthropic API key to .env.local${RESET}"
echo "  Get it at: console.anthropic.com"
echo ""
read -p "Paste your ANTHROPIC_API_KEY now (or press Enter to skip): " ANTHROPIC_KEY
if [ -n "$ANTHROPIC_KEY" ]; then
  sed -i.bak "s|sk-ant-REPLACE_ME|$ANTHROPIC_KEY|" .env.local && rm .env.local.bak
  ok "Anthropic API key set"
fi

# ─── VERCEL ───────────────────────────────────────────────────
step "3/3 — Deploying to Vercel"

if ! vercel whoami &>/dev/null; then
  echo "Opening Vercel login..."
  vercel login
fi

# Set environment variables in Vercel
vercel env add ANTHROPIC_API_KEY production <<< "$(grep ANTHROPIC_API_KEY .env.local | cut -d= -f2)"
vercel env add NEXT_PUBLIC_SUPABASE_URL production <<< "$SUPABASE_URL"
vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production <<< "$ANON_KEY"
vercel env add SUPABASE_SERVICE_ROLE_KEY production <<< "$SERVICE_KEY"
vercel env add NEXT_PUBLIC_APP_URL production <<< "https://$VERCEL_PROJECT_NAME.vercel.app"

# Deploy
DEPLOY_URL=$(vercel --prod --name "$VERCEL_PROJECT_NAME" --yes 2>&1 | grep "https://" | tail -1)
ok "Deployed: $DEPLOY_URL"

# ─── DONE ─────────────────────────────────────────────────────
echo ""
echo "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
echo "${GREEN}${BOLD}  CareerSwarm is live!${RESET}"
echo "${GREEN}${BOLD}════════════════════════════════════════${RESET}"
echo ""
echo "  GitHub:    https://github.com/$GITHUB_USER/$REPO_NAME"
echo "  Supabase:  $SUPABASE_URL"
echo "  App:       $DEPLOY_URL"
echo ""
echo "  DB password saved to: .supabase-db-password.txt"
echo "$SUPABASE_DB_PASSWORD" > .supabase-db-password.txt
echo ""
echo "  Next: Update Supabase auth redirect URLs"
echo "  Supabase Dashboard → Auth → URL Configuration"
echo "  Site URL:     $DEPLOY_URL"
echo "  Redirect URL: $DEPLOY_URL/api/auth/callback"
echo ""
